apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - image: snehalatha15/healthcare:latest
          name: healthcare ctr
          ports:
            - containerPort: 8082

